### ISSUE TITLE
Gulp / Grunt tasks

### ISSUE THREAD

**Issue by JuhQ** [axemclion/protractor-perf#1]
How would one use this with gulp or grunt?

**Comment by axemclion** [comment]
I looked at [grunt-protractor-runner](https://www.npmjs.org/package/grunt-protractor-runner), but looks like it internally looks for the CLI and runs that. Looks like that is the same case for gulp-protractor. 

They both look for the protractor installer. We could create separate gulp and grunt tasks for protractor-perf in this repo. Will that work for you ?

**Comment by wlsf82** [comment]
I think we can a least try.

2014-11-18 17:57 GMT-02:00 Parashuram N notifications@github.com:

> I looked at grunt-protractor-runner
> https://www.npmjs.org/package/grunt-protractor-runner, but looks like
> it internally looks for the CLI and runs that. Looks like that is the same
> case for gulp-protractor.
> 
> They both look for the protractor installer. We could create separate gulp
> and grunt tasks for protractor-perf in this repo. Will that work for you ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/axemclion/protractor-perf/issues/1#issuecomment-63534304
> .

## 

Walmyr Lima e Silva Filho
(48) 9133-5199

**Comment by JuhQ** [comment]
I think you should totally do that.

**Comment by BenFlanagan** [comment]
+1. This would be very useful.

**Comment by axemclion** [comment]
Did not have time to get to this. Would greatly appreciate a pull request if someone has cycles to work on this :smile:

**Comment by BenFlanagan** [comment]
I'd love to but it'll be a steep learning curve for me, which I might not get around to any time soon either ;) ... node packages are definitely on my "to learn" list though.

**Comment by iljapavlovs** [comment]
would really appreciate this one!

**Comment by axemclion** [comment]
There is a PR for Grunt - I am looking to merge it. Would be great if we have a similar PR for Gulp too !!

**Comment by theandrewlane** [comment]
Gulp implementation, anyone?

**Comment by axemclion** [comment]
We now have a Grunt task, and I have published it.

We will also need a Gulp task for it now.

**Comment by robinj** [comment]
If nobody has picked this up yet then I will since I will be needing it within the next couple of weeks

**Comment by axemclion** [comment]
@robinj Saw your comment in the notification, but it seems to be gone now. No one has picked it up, so please go for it ! :)

**Comment by JuhQ** [comment]
I think this issue can be closed now that there is an grunt plugin.
If gulp plugin is needed, open a new issue.
