### ISSUE TITLE
Do I have a way to save my metrics obtained from protractor-perf in MySQL database or any other database?

### ISSUE THREAD

**Issue by challapruthvi** [axemclion/protractor-perf#10]
I am planning to save my metrics obtained from protractor-perf into a database and build a dashboard which would give a good GUI for the users / developers regarding the performance of the web pages.

But, I am not sure whether there is a way for protractor-perf to do this ?? I have done my research and found out regarding " Perfjankie " . But I am curious whether it can be used with protractor-perf ? 

As I could see Perfjankie as a monitoring tool which runs based on Browser-perf. So I am guessing there should be a way for protractor-perf to use this tool directly as protractor-perf is based on Browser-perf. Please let me know any info regarding this.

Thank you.

**Comment by axemclion** [comment]
`perfjankie` automatically saves the metrics in a couchdb database. `protractor-perf` was meant to _test_ performance regressions and hence does not have a built in way to save the metrics. You could always do `getStats` and save the metrics I guess.

**Comment by challapruthvi** [comment]
So, It is not possible to use perfjankie using protractor-perf. 

Can you guide me on how to save the getStats onto my own database ? I would like to automate saving the metrics obtained from each page of testing and save them into my database. Is there any way to connect to a database internally using protractor-perf ?

**Comment by axemclion** [comment]
`protractor-perf` does not have a database connection, so you would have to write the code to connect to a database and send the data over. I guess this would be just like any other database code from node that you would write.

**Comment by challapruthvi** [comment]
Ok. I will try to write the database connection code . But Will I be able to use perfjankie tool ? 

protractor-perf --> SomeDB (couchDB, MongoDB, any possible DB) --> Perfjankie Tool ??

Is the above flow possible ? Especially the last step i.e., Can we use perfjankie Tool to display the dashboard by getting the data from some external DB where I have stored my Metrics Information which I got from protractor-perf ??
