### ISSUE TITLE
Does Protractor-perf give any Special metrics additional to the normal ones when testing Angular Pages ?

### ISSUE THREAD

**Issue by challapruthvi** [axemclion/protractor-perf#13]
I have a doubt regarding the metrics provided by protractor-perf. Normally, when I try to load the URL I am getting the following set of metrics:

---

{ numAnimationFrames: 34,
  numFramesSentToScreen: 34,
  droppedFrameCount: 0,
  meanFrameTime: 15.745085717312028,
  framesPerSec_raf: 63.5118803386685,
  unloadEventEnd: 0,
  responseEnd: 1433186737166,
  responseStart: 1433186737165,
  domInteractive: 1433186737274,
  domainLookupEnd: 1433186737131,
  unloadEventStart: 0,
  domComplete: 1433186737393,
  domContentLoadedEventStart: 1433186737274,
  domainLookupStart: 1433186737131,
  redirectEnd: 0,
  redirectStart: 0,
  connectEnd: 1433186737157,
  connectStart: 1433186737131,
  loadEventStart: 1433186737393,
  navigationStart: 1433186736854,
  requestStart: 1433186737157,
  secureConnectionStart: 1433186737132,
  fetchStart: 1433186737089,
  domContentLoadedEventEnd: 1433186737274,
  domLoading: 1433186737167,
  loadEventEnd: 1433186737406,
  firstPaint: 229.165077209473,
  Layers: 1,
  PaintedArea_total: 234087,
  PaintedArea_avg: 234087,
  NodePerLayout_avg: 0,
  ExpensivePaints: 0,
  ExpensiveEventHandlers: 0,
  GPUTask: 6.627,
  GPUTask_avg: 1.3254,
  GPUTask_max: 6.124,
  GPUTask_count: 5,
  Program: 16.931,
  Program_avg: 0.12358394160583942,
  Program_max: 2.915,
  Program_count: 137,
  FireAnimationFrame: 2.203,
  FireAnimationFrame_avg: 0.09179166666666666,
  FireAnimationFrame_max: 0.432,
  FireAnimationFrame_count: 24,
  FunctionCall: 7.570000000000001,
  FunctionCall_avg: 0.2703571428571429,
  FunctionCall_max: 2.515,
  FunctionCall_count: 28,
  RequestAnimationFrame: 24,
  UpdateCounters: 28,
  UpdateLayerTree: 23,
  CompositeLayers: 0.9110000000000003,
  CompositeLayers_avg: 0.039608695652173925,
  CompositeLayers_max: 0.149,
  CompositeLayers_count: 23,
  Paint: 0.199,
  Paint_avg: 0.199,
  Paint_max: 0.199,
  Paint_count: 1,
  PaintImage: 0.020999999999999998,
  PaintImage_avg: 0.006999999999999999,
  PaintImage_max: 0.015,
  PaintImage_count: 3,
  'Draw LazyPixelRef': 1,
  UpdateLayer: 0.286,
  UpdateLayer_avg: 0.286,
  UpdateLayer_max: 0.286,
  UpdateLayer_count: 1,
  AnalyzeTask: 0.038,
  AnalyzeTask_avg: 0.038,
  AnalyzeTask_max: 0.038,
  AnalyzeTask_count: 1,
  RasterTask: 0.213,
  RasterTask_avg: 0.213,
  RasterTask_max: 0.213,
  RasterTask_count: 1 }

---

For the next page(which is an angular page) I would like to automate some operations on that. Will I be able to get any different additional metrics as the testing has been done on Angular page ?? or else is it going to be just the same set of metrics data as the above one.

Does protractor-perf has such a feature where some additional metrics gets added when testing angular pages ??

Thanks in Advance.

**Comment by axemclion** [comment]
Protractor-perf is built on top of browser-perf and does not add any special metrics. All these metrics are the same you would get when looking at the browser's developer tools.
