### ISSUE TITLE
Crash with ECONNREFUSED on perfRunner.start()

### ISSUE THREAD

**Issue by ewing77** [axemclion/protractor-perf#2]
I have a rather annoying issue with protractor-perf, which I couldn't get to the ground.

Starting the test with a manual started selenium server works smoothly. But letting protractor start selenium via Jar or using directconnect crashes with:

```
Error: [execute("(function(){var getTimeMs=(function(){if(window.performance)\nreturn(performance.now||performance.mozNow||performance.msNow||performance.oNow||performance.webkitNow).bind(window.performance);else\nreturn function(){return new Date().getTime();};})();var requestAnimationFrame=(function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60);};})().bind(window);window.__RafRecorder={frames:[],flush:true,record:function(timeStamp){if(__RafRecorder.flush){__RafRecorder.frames=[];__RafRecorder.flush=false;}\n__RafRecorder.frames.push(timeStamp);requestAnimationFrame(__RafRecorder.record);},get:function(){__RafRecorder.flush=true;return __RafRecorder.frames;}};requestAnimationFrame(window.__RafRecorder.record);}());")] connect ECONNREFUSED
```

I tried it with Chromium binary as well as with Chrome Canary.

I didn't found any difference between the automatic start and the manual selenium start, where I grabbed the exec call from an automatic start, so they are identical. Also the running user etc seems all identical.

I also traced the chromedriver verbose output in both cases and the only difference is, that in the manual start case, the driver gets an executeScript call:

```
[6.725][INFO]: Done waiting for pending navigations
[6.725][INFO]: RESPONSE ExecuteScript null
[7.044][INFO]: COMMAND ExecuteScript {
   "args": [  ],
   "script": "(function(){var getTimeMs=(function(){if(window.performance)\nreturn(performance.now||performance.mozNow||performance.msNow||performance.oNow||performance.webkitNow).bind(window.performance);else\nre..."
}
[7.055][DEBUG]: DEVTOOLS EVENT Timeline.eventRecorded {
```

while by using directconnect it gets a quit call at that step:

```
[5.504][INFO]: Done waiting for pending navigations
[5.504][INFO]: RESPONSE ExecuteScript null
[5.619][INFO]: COMMAND Quit {

}
[5.721][INFO]: RESPONSE Quit
```

In order to make sure, that neither my application nor the testscript causes the issue, I isolated my testcase and used only the angular.js example.

package.json (using 1.4.0 as protractor_perf is fixing it to 1.4.0 and is failing to find the driver when versions differ)

```
{
  "name": "properf_test",
  "version": "0.0.0",
  "description": "A test for protractor_perf",
  "devDependencies": {
    "protractor": "~1.4.0",
    "protractor-perf": "*"
  },
  "scripts": {
    "preperftest": "npm run update-webdriver",
    "perftest": "protractor-perf protractor-perf.conf.js",
    "preupdate-webdriver": "npm install",
    "update-webdriver": "webdriver-manager update",
    "start-webdriver": "webdriver-manager start"
  }
}
```

protractor-perf.conf.js (used underscores to "comment out" running variants")

```
exports.config = {
    _seleniumAddress: 'http://localhost:4445/wd/hub',
    _seleniumPort: 4445,
    _directConnect: true,

    specs: [
        'tests/perf/*.spec.js'
    ],

    capabilities: {
        browserName: 'chrome',
        _chromeOptions: {
              binary: '/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary',
        }
    },
};
```

/tests/perf/example.spec.js

```
var PerfRunner = require('protractor-perf');
describe('angularjs homepage todo list', function() {
    var perfRunner = new PerfRunner(protractor);

    it('should add a todo', function() {
        browser.get('http://www.angularjs.org');

        perfRunner.start();

        element(by.model('todoText')).sendKeys('write a protractor test');
        element(by.css('[value="add"]')).click();

        perfRunner.stop();

        if (perfRunner.isEnabled) {
                    perfRunner.getStats('mean_frame_time').then(function(stats){console.log(stats)});
            //expect(perfRunner.getStats('meanFrameTime')).toBeLessThan(60);
        };

        var todoList = element.all(by.repeater('todo in todos'));
        expect(todoList.count()).toEqual(3);
        expect(todoList.get(2).getText()).toEqual('write a protractor test');

    });
});
```

Starting the test with: `npm run perftest`

Any way I can help with digging into the issue, please let me know.

Very keen to find the reason for this, as tests should run fully automatic without manual starting and stopping selenium server.

Btw. firefox doesn't work at all. It hangs and test times out.

**Comment by ewing77** [comment]
Btw. I updated browser-perf and protractor to the latest version in protractor-perf and fixed the resulting issues, but issue still persists with the same error.

├─┬ protractor@1.6.1
...
└─┬ protractor-perf@0.0.5
  ├─┬ browser-perf@1.2.1
...

**Comment by axemclion** [comment]
@ewing77 Thanks for reporting this issue and sorry for not being able to get to it earlier. I am investigating this now, will update if I need more info.

I am also assuming that you have protractor and protractor-perf installed globally ?

**Comment by iowrwr** [comment]
Hey, thanks for investigating. 

No I haven't installed them globally, and I even think it doesn't matter for this case. I was using the same resources when manually starting as the automated start was using. But if you like me to test with globally installed packages, I'm happy to do so, although it won't fit to our use case later on.

Btw. I switched github account. ewing77 was an old private github account.

**Comment by guyzi** [comment]
I am experiencing the same problem. Both are installed globally

**Comment by axemclion** [comment]
@guyzi You would need to install it locally also. That is how the require statement will find it. Is there a gist you have that I coudl investigate ?

**Comment by axemclion** [comment]
Created a repro here - https://gist.github.com/axemclion/8437d6c2b62adccb9d5c. `protractor` and `protractor-perf` are _NOT_ installed globally. I just did 

``` bash
git clone git@gist.github.com:/8437d6c2b62adccb9d5c.git
npm run perftest

```

Confirming that I am seeing this error. Looking at possible causes.

**Comment by axemclion** [comment]
Webdriver-manager start selenium at any port on localhost. Since this is not specified in selenium server, selenium by default looks at port at http://localhost:4444, causing this error.

**Comment by axemclion** [comment]
Fixed this issue - Just specify a `seleniumPort: 4445` and `selenium: 'http://localhost:4445/wd/hub'` in the config. This basically tells which port should be used for the selenium, and that information is passed over to `perf.start()` methods. 

If this does not fix your issue, please repoen and add a repro.

**Comment by Mellbourn** [comment]
We are still having this problem. 
Unfortunately specifying the `seleniumPort` and `selenium` as you suggest does not make any difference. `perf.start` still crashes as for OP.
Our environment is large, complex and closed source, so it is hard to post a repro with it.

**Comment by axemclion** [comment]
@Mellbourn It would be hard to debug without a repro - can you create a new, reduced project that has similar issue so that I can help debug ?

**Comment by iowrwr** [comment]
I just saw the reply of the reply and tested the outcome of the reply. It indeed does not crash on my side, at least not with the same error message. But I had to adjust the used browser to a very specific version. it did not work with Chromium 38.

It quit with: 
`UnknownError: unknown error: Chrome version must be >= 39.0.2171.0`

So I used Canary with the result: 
`UnknownError: unknown error: unhandled inspector error: {"code":-32000,"message":"Timeline is deprecated. Please use Tracing instead"}`

Finally, Chromium 41:
`expect(perfRunner.getStats('mean-frame-time')).toBeLessThan(60);`
quits with: 
`Expected undefined to be less than 60.`

However, from looking at the stats, it seems to be replaced by meanFrameTime. So the next test:
`expect(perfRunner.getStats('meanFrameTime')).toBeLessThan(60);`
quits with:
`1 test, 3 assertions, 0 failures`

So works for me. But limited to Chrome 41, which will not work as an option for very long. But at least, I would rate this ticket to be fixed from my side. 

@Mellbourn, would be interesting if you really face the same issue, and whether your setup is correct, e.g. mine is:

```
exports.config = {
    selenium: 'http://localhost:4445/wd/hub',
    seleniumPort: 4445,
    specs: [
        'tests/perf/*.spec.js'
    ],
    capabilities: {
        browserName: 'chrome',
        chromeOptions: {
              binary: '/Applications/Chromium41.app/Contents/MacOS/Chromium'
        }
    },
};
```

**Comment by Mellbourn** [comment]
Ironically, it is Chrome 41 we are using (Google chrome portable on windows, to be specific).

This is my config:

``` JavaScript
exports.config = {
    seleniumPort: 4445,
    selenium: "http://localhost:4445/wd/hub",
    seleniumServerJar: "../../../node_modules/protractor/selenium/selenium-server-standalone-2.45.0.jar",
    baseUrl: 'http://localhost:9000/browser2rest.html',
    capabilities: 
        {
            "browserName": "chrome",
            "chromeOptions": {
                "binary": "tools\\GoogleChromePortable\\GoogleChromePortable.exe"
            }
        },
    directConnect: true,
}
```

**Comment by iowrwr** [comment]
Remove the directConnect. It fails for me too that way.

**Comment by Mellbourn** [comment]
Sorry, removing directConnect doesn't make any difference for me.

I get the same error as before:

```
Error: [execute("(function(){if(typeof window.chrome!=='undefined'){window.webkitRequestAnimationFrame(function(){window.__navTimings=window.performance.timing;var first_paint_secs=window.chrome.loadTimes().firstPaintTime-window.chrome.loadTimes().startLoadTime;window.__navTimings.__firstPaint=first_paint_secs*1000;});}else if(typeof window.performance!=='undefined'&&typeof window.performance.timing.msFirstPaint!=='undefined'){window.setTimeout(function(){window.__navTimings={__firstPaint:window.performance.timing.msFirstPaint-window.performance.timing.navigationStart};for(var key in window.performance.timing){window.__navTimings[key]=window.performance.timing[key]}},1000);}else if(typeof window.performance!=='undefined'&&typeof window.performance.timing!=='undefined'){window.__navTimings=window.performance.timing;}else{window.__navTimings={};}}());")] Not JSON response
```

Note that it ends with

```
Not JSON response
```

**Comment by iowrwr** [comment]
Please note, this is a different error message than the initial one. Could you check the minimal testcase from this error report and in case it works, find the trigger in your test case or as axemclion requested, create a minimal testcase that showcases your error?

**Comment by axemclion** [comment]
@iowrwr Looks like Chrome is removing Timeline, and replacing with Tracing. I am working on this update - need to figure out how not to break existing Chrome versions :(

**Comment by iowrwr** [comment]
@axemclion As selenium or chrome driver has already deprecated Chrome <39 I would not spend time on backward compat, as even Chromium 38 seems to have tracing on board.

**Comment by Mellbourn** [comment]
When I try to reproduce it in a super simple scenario, I get

``` JavaScript
node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:113
  var template = new Error(this.message);
                 ^
SessionNotCreatedError: session not created exception
from unknown error: unhandled inspector error: {"code":-32000,"message":"Timeline is deprecated. Please use Tracing instead"}
```

Is that what you are referring to when you say that Chrome is removing Timeline?

Btw, is it absolutely necessary to install protractor-perf globally? That setup will not work for us.

**Comment by iowrwr** [comment]
Yes. This is what he meant. But it also means, you seem to use a Chrome version >41.

On my side the following test ...

```
var PerfRunner = require('protractor-perf');
describe('angularjs homepage todo list', function () {
    var perfRunner = new PerfRunner(protractor, browser);

    it('should add a todo', function() {
        browser.driver.executeScript(function() {
            return window.navigator.appVersion.match(/Chrome\/(.*?) /)[0];
        }).then(function(result) {
            console.log('browser: ' + result);
        });
    });
});
```

results in ...

```
browser: Chrome/41.0.2272.101
.

Finished in 0.746 seconds
1 test, 0 assertions, 0 failures
```

**Comment by axemclion** [comment]
You dont have to install protractor-perf globally - you can always run it as node_mobules/.bin/protractor-perf conf.js

**Comment by axemclion** [comment]
We already have a pull request for this here - https://github.com/axemclion/browser-perf/pull/30
