### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by umagsfx** [axemclion/protractor-perf#20]
I am seeing the below issue with the latest version. Could you please check this one ?

protractor-perf test/conf.js
env: node\r: No such file or directory

I have downgraded the version to 0.1.8 but i am seeing the below issue.

Error: No selenium server jar found at the specified location (/usr/local/lib/node_modules/protractor-perf/node_modules/protractor/selenium/selenium-server-standalone-2.45.0.jar). Check that the version number is up to date.

**Comment by axemclion** [comment]
Just released an updated version.
