### ISSUE TITLE
UnknownError - An unknown server-side error occurred while processing the command.

### ISSUE THREAD

**Issue by umagsfx** [axemclion/protractor-perf#22]
I am running tests on SauceLabs where I see the below issue. Could you please help me out?

https://gist.github.com/umagsfx/8edffe6d69216120ebf0

 Failed: [logTypes()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
    System info: host: 'sfx-uma.local', ip: '192.168.232.200', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_60'
    Driver info: driver.version: unknown

**Comment by umagsfx** [comment]
I stuck at this point. Could you please help me out?

**Comment by axemclion** [comment]
Can you check if you able to connect to saucelabs directly, without protractor-perf ?

**Comment by umagsfx** [comment]
Yes. I am able to run the scenarios with protractor.

**Comment by umagsfx** [comment]
Hi, 

Are you back ?
Could you please help me on this one ?

**Comment by axemclion** [comment]
@umagsfx Yes, I am back from vacation and will look at this sometime this week.

**Comment by umagsfx** [comment]
Thanks for your kind reply. 
Sure.

**Comment by axemclion** [comment]
Looked over this issue on email. The issue here is that the defaultTimeoutInterval for jasmineNodeOpts set in the protractor configuration was way too low. Increasing that fixes this issue. 

Hence closing, plesae reopen the issue if this is still a problem.

**Comment by chintamaniaphale** [comment]
I am getting an error :
Stack:
Error: [logTypes()] Error response status: 13, , UnknownError - An unknown s
rver-side error occurred while processing the command. Selenium error: Command
ot found: GET /session/794a23f4-0d72-451b-af0e-3dba829e2f4c/log/types
Command duration or timeout: 2 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'IBM903-PB61XBM', ip: '9.79.148.87', os.name: 'Windows 7'
My

jasmineNodeOpts: {

defaultTimeoutInterval: 10000000,
}

is set pretty high . still facing the problems Could you please check?
