### ISSUE TITLE
multiple protractor-perf operations in one protractor test case.

### ISSUE THREAD

**Issue by Danli741** [axemclion/protractor-perf#24]
The protractor test case is like this:

``` javascript
describe("TEST", function() {
    it("test1", function() {
        var perfRunner = new PerfRunner(protractor, browser);
        perfRunner.start();
        // test, like click....
        perfRunner.stop();
        if (perfRunner.isEnabled) {
            perfRunner.getStats().then(function(data) {
                        /////
            });
        }
    });

    it("test2", function() {
        var perfRunner = new PerfRunner(protractor, browser);
        perfRunner.start();
        // test, like click....
        perfRunner.stop();
        if (perfRunner.isEnabled) {
            perfRunner.getStats().then(function(data) {
                        /////
            });
        }
    });
// .....
});

```

The problem is that: the result is a little weird. The metrics, like readystart of each test ('test1', 'test2'...) are the same (test1.readystart == test2.readystart, test1.navigationstart == test2.navigationstart). 
I don't know if I misunderstand the usage of protractor-perf/ browser-perf here...
Could you please help me with it? :) 
Thanks.

**Comment by dpramar** [comment]
There are some metrics that doesn't play well with AngularJS and that's the case for most of the [navigation timing metrics](https://github.com/axemclion/browser-perf/wiki/Metrics#navtimingmetrics).
This is because AngularJS is loaded only once and after the first load it only manipulates the DOM, therefore those properties of navigation timing are not updated since they depend on load events.

**Comment by Danli741** [comment]
Thanks for your quick reply. hmm But can I say that some metrics, like 'firstPaint', 'NetworkXHRRequest', 'DomReady'..., are still valid here to use?

**Comment by axemclion** [comment]
The metrics above are per page. Looks like in your tests, you are already loading the page. That is the reason they are the same. 

The metrics you mention above do not really test the characteristics of actions like clicks. Can you explain a little more on what exactly are you looking to test ?

**Comment by axemclion** [comment]
Closing the issue assuming that the question is answered. Please re-open if the answer is not satisfactory.

**Comment by sadanandGithub123** [comment]
Hi all When i am launching my test script using "protractor-perf conf.js" getting an error --

> <--- Last few GCs --->
> 
>    54047 ms: Scavenge 1320.0 (1360.0) -> 1320.0 (1360.0) MB, 0.0 / 0 ms (+ 1.0 m
> s in 1 steps since last GC) [allocation failure] [incremental marking delaying m
> ark-sweep].
>    54425 ms: Mark-sweep 1320.0 (1360.0) -> 1065.3 (1106.1) MB, 377.9 / 0 ms (+ 1
> .0 ms in 2 steps since start of marking, biggest step 1.0 ms) [last resort gc].
>    54787 ms: Mark-sweep 1065.3 (1106.1) -> 1065.3 (1106.1) MB, 362.0 / 0 ms [las
> t resort gc].
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 000000E867C373A9 <JS Object>
>     2: /* anonymous */(aka /* anonymous */) [D:\Automation\ProtractDemo\node_mod
> ules\protractor-perf\node_modules\browser-perf\node_modules\wd\lib\utils.js:~102
> ] [pc=0000013B6B29F47F] (this=000000E867C04131 <undefined>,i=49901230)
>     3: times [D:\Automation\ProtractDemo\node_modules\protractor-perf\node_modul
> es\browser-perf\node_modules\wd\node_modules\lodash\index.js:~11490] [pc=0000013
> B6BC...
> 
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

I am getting this error when it is calling 

> perfRunner.start()

  second time
