### ISSUE TITLE
Process Out of memory while running Protractor Perf

### ISSUE THREAD

**Issue by aicodess** [axemclion/protractor-perf#25]
Hi 
I am using protractor-perf to measure performance for my angular application 
i am using perfRunner.start(); and perfRunner.stop(); two places 
when its called first time , working good but at second second time , i am getting error as-

> <--- Last few GCs --->
> 
>    77396 ms: Scavenge 1183.3 (1223.3) -> 1183.3 (1223.3) MB, 0.1 / 0 ms (+ 2.0 m
> s in 1 steps since last GC) [allocation failure] [incremental marking delaying m
> ark-sweep].
>    77739 ms: Mark-sweep 1183.3 (1223.3) -> 928.7 (969.4) MB, 342.7 / 0 ms (+ 2.0
>  ms in 2 steps since start of marking, biggest step 2.0 ms) [last resort gc].
>    78064 ms: Mark-sweep 928.7 (969.4) -> 928.7 (969.4) MB, 325.2 / 0 ms [last re
> sort gc].
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 000000BE60A373A9 <JS Object>
>     2: /\* anonymous _/(aka /_ anonymous */) [D:\Automation\ProtractDemo\node_mod
> ules\protractor-perf\node_modules\browser-perf\node_modules\wd\lib\utils.js:~102
> ] [pc=000003E4A4F230BF](this=000000BE60A04131 <undefined>,i=49901230)
>     3: times [D:\Automation\ProtractDemo\node_modules\protractor-perf\node_modul
> es\browser-perf\node_modules\wd\node_modules\lodash\index.js:~11490] [pc=000003E
> 4A50...
> 
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
# Code Snippet for second call--

> perfRunner.start();
>   element(by.id('quote_owner:first_name')).sendKeys('Test');
>   browser.driver.findElement(By.xpath('//*[@id="quote_owner:postal_code"]')).sendKeys('1000');
>   element(by.id('quote_owner:birth_date')).click();

**Comment by axemclion** [comment]
Looks like the trace file is pretty huge. I would suggest trying the following
1. See if you can shorten the test case. This will collect less logs
2. Use something like `--max_old_space_size` to increase the heap size in node
3. Use only the metrics you would like to test against.

**Comment by aicodess** [comment]
Thanks @axemclion for your response 
1) Unfortunately i can not shorten my test case .
2) about heap size i also found so many solutions to increase   --max_old_space_size , but i m not finding any clue to set it against to Protractor-Perf . 

Please suggest how can i set --max_old_space_size value in perotarctor-perf .

**Comment by amangrover1** [comment]
facing same issue, where can i increase memory. please let me know.
I am running protractor and using webstorm and facing issue comparing big JSON files.
