### ISSUE TITLE
trying to get protractor-perf running in my environment

### ISSUE THREAD

**Issue by maj2002** [axemclion/protractor-perf#29]
Copied the following lines into my spec file:

var ProtractorPerf = require('protractor-perf');
var perf = new ProtractorPerf(protractor, browser); // Initialize the perf runner

When I try to run with _just_ protractor, after I have instrumented a spec file, I ger the error:
 "Cannot find module 'protractor-perf'"        (I do have the location of protractot-perf in my PATH).

When I try to run with "protractor-perf" I get an error:

```
                    if (typeof browserConfig[passedBrowser.browserName] !== 'undefined') {
                                                          ^
```

TypeError: Cannot read property 'browserName' of undefined
    at C:\Users\mjackson1\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\browser-perf\lib\options.js:84:42
    at Array.forEach (native)
    at opts.accesskey (C:\Users\mjackson1\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\browser-perf\lib\options.js:79:18)
    at C:\Users\mjackson1\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\browser-perf\lib\options.js:197:10
    at Array.forEach (native)
    at Object.module.exports.scrub (C:\Users\mjackson1\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\browser-perf\lib\options.js:196:14)
    at new Runner (C:\Users\mjackson1\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\browser-perf\lib\runner.js:12:22)
    at Function.module.exports.getConfig (C:\Users\mjackson1\AppData\Roaming\npm\node_modules\protractor-perf\lib\index.js:89:15)
    at Object.<anonymous> (C:\Users\mjackson1\AppData\Roaming\npm\node_modules\protractor-perf\lib\cli.js:149:15)
    at Module._compile (module.js:434:26)

**Comment by afterbangx** [comment]
I had this same issue today. I fixed it using the following in my conf.js.

```
capabilities: {
    browserName: "chrome"       
}
```

**Comment by axemclion** [comment]
@maj2002 Using `browser:'chrome'` as @afterbangx said should fix it. Closing this issue as fixed, but if you think that still does not fix it, please do re-open.

**Comment by aluzardo** [comment]
I am getting the same problem. I am using multiCapabilites:

```
    multiCapabilities: [
        {
            browserName: 'firefox'
        },
        {
            browserName: 'chrome'
        }
    ],
```

How can I fix it?

**Comment by axemclion** [comment]
@jahnavi310 fixed this issue as a part of https://github.com/axemclion/protractor-perf/issues/35. Can you check if that works for you ?

**Comment by jahnavi310** [comment]
@axemclion : i tried bumping the version on npm, but for reason it is still 0.2.1 on npm, can you try bumping and publishing it on your side?

**Comment by axemclion** [comment]
My bad, i thought 0.2.2 was done. Now published it.

@jahnavi310 You have been working with the project a lot. Would you like to also become a committer on the project ? I am sure you will be able to help other folder.

**Comment by jahnavi310** [comment]
@axemclion : definitely...
