### ISSUE TITLE
Not getting all metrics back when running with Protractor

### ISSUE THREAD

**Issue by joehaines** [axemclion/protractor-perf#30]
Hi,

I'm not getting all of the test results back when running through protractor using the example test code (https://gist.github.com/axemclion/9594795).

If I run through node directly I seem to get all of them.

Specifically interested in all of the metrics unrelated to network, so I'm passing in the metrics: ['TimelineMetrics', 'ChromeTracingMetrics'] param and from node I get a big long list of things, running from protractor I just get two back - { Styles: 0, Javascript: 0 }.

Anything obvious I might have messed up?

Thanks in advance

**Comment by axemclion** [comment]
Can you run `browser-perf` and see if that is generating the required metrics on the page ?
