### ISSUE TITLE
How to stop protractor-perf running on a selenium grid to fire up a standalone selenium server

### ISSUE THREAD

**Issue by jahnavi310** [axemclion/protractor-perf#33]
So, when i try and run perf on a selenium grid that is generated via a docker grid, this is what i get:

```
  ✗ Starting to record metrics... (0.317 sec)
[chrome #01-1]         - Failed: [logTypes()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
[chrome #01-1] System info: host: 'MAC1837.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.4', java.version: '1.7.0_79'
[chrome #01-1] Driver info: driver.version: unknown
[chrome #01-1]         System info: host: 'MAC1837.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.4', java.version: '1.7.0_79'
[chrome #01-1]         Driver info: driver.version: unknown

```

this happens when i have this in my ptor config file:
`seleniumAddress: 'http://localhost:4444/wd/hub` - this is the grid hoisted via docker

changing the above to:

`selenium: 'http://mygirdaddress:4444/wd/hub',
    seleniumPort: 4444,
`
forces it to fire up a local instance of the browser and starts the selenium-standalone server.
Is there anyway to capture the same metrics on the headless browsers that are running on the grid?

**Comment by axemclion** [comment]
@jahnavi310 Was this not an issue ? Were you able to resolve this?

**Comment by jahnavi310** [comment]
yep, this was resolved.
