### ISSUE TITLE
not working with multiCapabilities in config file

### ISSUE THREAD

**Issue by jahnavi310** [axemclion/protractor-perf#35]
I have the following in my config file:

```
   multiCapabilities: [
        // firefox - downgrade to firefox 45.0.1 if you need to make it work locally
        // {
        //     browserName: 'firefox',
        //     shardTestFiles: true,
        //     maxInstances: 10
        // },
        //max-desktop-chrome - default screen size
        {
            browserName: 'chrome',
            shardTestFiles: true,
            maxInstances: 10,
            chromeOptions: {
                args: ['--lang=en',
                    '--window-size=1024,3000', '--disable-extensions']
            }
        }
]
```

This gives me the following error:

```
node_modules/browser-perf/lib/options.js:84
            if (typeof browserConfig[passedBrowser.browserName] !== 'undefined') {
                                                  ^

TypeError: Cannot read property 'browserName' of undefined
```

This only gets resolved if i replace multiCapabilities with capabilities.

Any idea? Is there no support to test against multi browsers?

**Comment by axemclion** [comment]
@jahnavi310 Chrome is the only one supported today, and the config expects capabilities. Can you not send an array in capabilities ? Also, you could send in a pull request if multi-capabilities needs to be supported and I can merge it in.

**Comment by jahnavi310** [comment]
According to this post: https://github.com/angular/protractor/blob/master/docs/browser-setup.md

it seems like multiCapabilities is needed to test against multiple browsers.

**Comment by jahnavi310** [comment]
so even if i send in`multicapabilities` having an array of browsers that has chrome and firefox, it wont work for firefox right?

**Comment by axemclion** [comment]
@jahnavi310 It will work for FIrefox, but the metrics that you get would be different.
Chrome has the richest set of metrics, and Firefox is a little less rich. You could run browser-perf from the command line to see the set of metrics that you get.

**Comment by jahnavi310** [comment]
@axemclion i just submitted a PR, take a look and let me know.

**Comment by axemclion** [comment]
@jahnavi310 I don't see a PR .

**Comment by jahnavi310** [comment]
@axemclion : my bad... there you go

**Comment by jahnavi310** [comment]
there should be one now

**Comment by axemclion** [comment]
Merged it in, thanks for the PR. Closing this issue since it is merged.

**Comment by jahnavi310** [comment]
do you also need to bump the npm version? @axemclion

**Comment by axemclion** [comment]
yeah, need to bump npm version and push it to the npm registry.
