### ISSUE TITLE
protractor-perf/browser-perf metrics v/s webpagetest metrics

### ISSUE THREAD

**Issue by jahnavi310** [axemclion/protractor-perf#37]
This is not an issue but more of a question, When I see the test metrics as opposed to when its run on the webpagetest website, the first param of the first view load time would be 5 seconds. what would the exact mapping be in protractor-perf? 

I did refer to this:

```
https://github.com/axemclion/browser-perf/wiki/Metrics
```

but i still cant figure out what the total time would be for the page to be fully loaded ??

**Comment by axemclion** [comment]
@jahnavi310 What is the exact webPageTest metric called ? We may need to look into WebPageTest to see how that is codified. 

If it is speed index, there is a pull request in browser-perf that is for implementing speed index.

**Comment by jahnavi310** [comment]
@axemclion : This is the exact metric I am looking for:

Load Time:

The Load Time is the time from when the user started navigating to the page until the Document Complete event (usually when all of the page content has loaded).

https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/quick-start-quide#TOC-Fully-Loaded: - Its referenced here.

**Comment by jahnavi310** [comment]
@axemclion : any idea?

**Comment by axemclion** [comment]
@jahnavi310 In this case, this would be the time for DomContentLoaded. Technically, you don't even need a tool to get that info - that is already available in window.performance.timing.\* values. I think you should simply pick it up from there.
