### ISSUE TITLE
Obsolete deprecated protractor.getInstance()

### ISSUE THREAD

**Issue by Phoscur** [axemclion/protractor-perf#4]
Protractor has removed the method in version 1.5

**Comment by lam2558** [comment]
Can someone suggest on how to fix this inside the lib?

**Comment by axemclion** [comment]
I have looked at this, but have a bunch of other things before i can get to fixing this. Would really appreciate a pull request.

**Comment by Phoscur** [comment]
Well I'm not able to actually get any version of protractor-perf to run and a simple replace protractor.getInstance() -> protractor seems not to do the job (no error message). Iams question remains.

**Comment by axemclion** [comment]
I ran this with protractor@1.3.0, seems to work. What is the error you get ?

**Comment by lam2558** [comment]
I think the issue here is that its referring to a deprecated method.

 TypeError: Object #<Object> has no method 'getInstance'

var ProtractorPerf = function(protractor) {
    this.sessionId = null;
    this.protractor = protractor;
    var conf = protractor.getInstance().params;

**Comment by lam2558** [comment]
@Phoscur , i try using browser-perf instead and it work
aexmclion wrote an example here:: https://gist.github.com/axemclion/9594795

**Comment by Phoscur** [comment]
Well I tried removing the getInstance() calls and running it like this with protractor [It's a cucumber setup]:

``` coffee-script
chai = require("chai")
chai.use(require("chai-as-promised"))
PtorPerf = require("protractor-perf")
should = chai.should()
By = protractor.By
Q = require 'q'
module.exports = ->
  perf = null
  @Before (done)->
    protractor.params = {perf: true};
    perf = new PtorPerf(protractor)
    perf.start()
    browser.manage().window().maximize()
    done()
  @After (done)->
    perf.stop()
    console.log('Performance statistics', perf.getStats('meanFrameTime'))
    done()

  @World.prototype.find = (selector)->
    browser.element(By.css(selector))

  @World.prototype.text = (where)->
    @find(where).getText()
```

It fails silently with error code 1 (no browser without logs doesn't maximize). 
I propably cheated to much without really reading your code..

I'm putting this back since it currently doesn't help me with my performance debugging right now, but it will be nice to establish to prevent further regressions.

**Comment by axemclion** [comment]
@Phoscur @lam2558  - This issue is now fixed, and it works with the latest version. Can you guys confirm if it works ?

**Comment by Phoscur** [comment]
It runs, after updating the local install (should only require global installation?)
But I can't read the stats (getStats). chai-should-as-promised seems to be not attached and resolving the promise manually gives undefined.
My current cucumber world:

``` coffee-script
ProtractorPerf = require('protractor-perf')
chai = require("chai")
chai.use(require("chai-as-promised"))
Q = require("q")
chai.should()
module.exports = ->

  @Before (done)->
    browser.driver.manage().window().maximize()
    @perf = new ProtractorPerf(protractor, browser)
    @perf.start()
    done()

  @After (done)->
    @perf.stop()
    if @perf.isEnabled
      #@perf.getStats('meanFrameTime').should.eventually.be.below(40) should is undefined
      @perf.getStats('meanFrameTime').then (s) ->
        console.log('meanFrameTime', s); # s is undefined
    done()


  @World.prototype.find = (selector)->
    browser.element(By.css(selector))
```
