### ISSUE TITLE
Crash with ECONNREFUSED on browser.controlFlow().execute()

### ISSUE THREAD

**Issue by krosti** [axemclion/protractor-perf#5]
I'm running the example located on this repo `/test` and when I run it returns this:

```
Error: [execute("(function(){var getTimeMs=(function(){if(window.performance)\nreturn(performance.now||performance.mozNow||performance.msNow||performance.oNow||performance.webkitNow).bind(window.performance);else\n
return function(){return new Date().getTime();};})();var requestAnimationFrame=(function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||
window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60);};})().bind(window);window.__RafRecorder={frames:[],flush:true,record:function(timeStamp)
{if(__RafRecorder.flush){__RafRecorder.frames=[];__RafRecorder.flush=false;}\n__RafRecorder.frames.push(timeStamp);
requestAnimationFrame(__RafRecorder.record);},get:function(){__RafRecorder.flush=true;return __RafRecorder.frames;}};requestAnimationFrame(window.__RafRecorder.record);}());")] connect ECONNREFUSED

Stacktrace:
     Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
From: Task: <anonymous>
    at [object Object].start (/Users/fernandocea/Development/web-ui/node_modules/protractor-perf/lib/index.js:53:37)
    at [object Object].<anonymous> (/Users/fernandocea/Development/web-ui/example.spec.js:7:16)
From: Task: Asynchronous test function: it()
Error
    at [object Object].<anonymous> (/Users/fernandocea/Development/web-ui/example.spec.js:5:3)
    at Object.<anonymous> (/Users/fernandocea/Development/web-ui/example.spec.js:2:1)

```

**(Driver info: chromedriver=2.10.267517,platform=Mac OS X 10.10.3 x86_64)**

**Comment by axemclion** [comment]
Related to https://github.com/axemclion/protractor-perf/issues/2 ?

**Comment by krosti** [comment]
Correct. Related to the global installation `npm install -g protractor-perf`, which fixed one issue and then related to the selenium port:

``` javascript
selenium: 'http://localhost:4445/wd/hub',
seleniumPort: 4445
```

thanks! :+1:

**Comment by axemclion** [comment]
You said that you saw in the documentation - is there a way to make the documentation clearer ? Would love if you could send in a pull request so that it makes it readable for other people who encounter the same error.

**Comment by iljapavlovs** [comment]
Hi @axemclion , @krosti. So what was the issue? 
So I need to install protractor globally and it will run via directConnect properly? I don`t need to have Selenium Server running?
I want to have:
1. running protractor-perf via directConnect, so without Selenium Server running. The reason is that I cannot connect to the Selenium Server since my corporate network is blocking the ip or the port. Btw, may be you know the solution to this problem - some kind of a proxy for selenium server?
2. protractor-perf installed only locally, since eventually this set up will be running on Jenkins.

**Comment by krosti** [comment]
@iljapavlovs 
About your first question, if you configure the protractor's server using `directConnect` on the `protractor_conf.js` file, the tool will test directly against Chrome and Firefox without using a Selenium Server. If you have your Selenium Server running on XXXX port and you have configured the same `url:port` on your `protractor_conf.js` file using the options `selenium: 'url:port', seleniumPort: 4445` the tool will detect it and will use that instance instead create a new one of the server.

Regarding the issue I suffered was particularly because I wasn't installed globally the `protractor-perf`, in my case.

You can find more info about Protractor's configurtion here: [Link](https://github.com/angular/protractor/blob/master/docs/server-setup.md).

Finally about the proxy, you can use this:

```
capabilities: {
  'proxy': {
    'proxyType': 'manual',
    'httpProxy': 'hostname.com:1234'
  }
}
```

or setup manually the flags like this:

```
http_proxy   http://user:password@proxy_url:port
https_proxy   http://user:password@proxy_url:port
```
