### ISSUE TITLE
protractor-perf command not found when installed locally

### ISSUE THREAD

**Issue by adokania** [axemclion/protractor-perf#6]
I have an existing set of protractor tests and was trying to configure this tool but when i run it i see "protractor-perf command not found" error. I see protractor-perf installed in my local node-modules directory, but i don't see a .bin directory immediately as a child of the protractor-perf directory.

**Comment by axemclion** [comment]
The .bin will be a child of the node_modules. For example, you will find protractor-perf as <PROJECT>/node_modules/.bin/protractor-perf.

**Comment by adokania** [comment]
What i see is myProject/node_modules/protractor-perf/node_modules/.bin/browser-perf..No protractor -perf in it

**Comment by axemclion** [comment]
Do you see myProject/node_modules/.bin ? This is in the index.js file as a command.

**Comment by adokania** [comment]
Thanks! that was it..

**Comment by axemclion** [comment]
Glad to be of help.
