### ISSUE TITLE
Undefined retruned when I try and console log the stats from protractor-perf 

### ISSUE THREAD

**Issue by adokania** [axemclion/protractor-perf#7]
I have a simple test that uses protractor-perf: 

```
pr.start();
browser.get('https://www.google.com');
pr.stop();

if (pr.isEnabled) {
  pr.getStats('mean-frame-time').then(function(stats){console.log(stats)});
};
```

the console shows undefined for the stats -- I have tried meanFrameTime and mean_frame_time. All of them shows undefined.

**Comment by axemclion** [comment]
What do you see if you just call `pr.getStats().then(console.log.bind(console))` ? Do you see all metrics ?

**Comment by adokania** [comment]
I do see the following, but none of this seems like a : 
{ fetchStart: 1432665953786,
  redirectStart: 0,
  domComplete: 1432665976307,
  redirectEnd: 0,
  loadEventStart: 1432665976307,
  navigationStart: 1432665953786,
  requestStart: 1432665953787,
  responseEnd: 1432665974173,
  secureConnectionStart: 0,
  domLoading: 1432665974179,
  domInteractive: 1432665976105,
  domainLookupEnd: 1432665953786,
  domContentLoadedEventStart: 1432665976105,
  loadEventEnd: 1432665976309,
  connectEnd: 1432665953786,
  responseStart: 1432665974171,
  unloadEventStart: 1432665974173,
  domContentLoadedEventEnd: 1432665976206,
  connectStart: 1432665953786,
  unloadEventEnd: 1432665974173,
  domainLookupStart: 1432665953786,
  firstPaint: 20759.1428756714,
  Program: 1193.4449999999558,
  Program_avg: 0.12792850251902196,
  Program_max: 106.246,
  Program_count: 9329,
  FireAnimationFrame: 123.69299999999933,
  FireAnimationFrame_avg: 0.09108468335787874,
  FireAnimationFrame_max: 3.674,
  FireAnimationFrame_count: 1358,
  FunctionCall: 229.89300000000142,
  FunctionCall_avg: 0.16503445800430827,
  FunctionCall_max: 98.244,
  FunctionCall_count: 1393,
  RequestAnimationFrame: 1367,
  UpdateCounters: 1529,
  UpdateLayerTree: 1410,
  CompositeLayers: 52.41000000000038,
  CompositeLayers_avg: 0.037978260869565496,
  CompositeLayers_max: 1.632,
  CompositeLayers_count: 1380,
  GCEvent: 25.516,
  GCEvent_avg: 3.645142857142857,
  GCEvent_max: 11.306,
  GCEvent_count: 7,
  GPUTask: 241.5349999999996,
  GPUTask_avg: 0.3182279314888005,
  GPUTask_max: 16.036,
  GPUTask_count: 759,
  EventDispatch: 109.369,
  EventDispatch_avg: 1.1047373737373738,
  EventDispatch_max: 100.618,
  EventDispatch_count: 99,
  ResourceSendRequest: 56,
  ResourceReceiveResponse: 56,
  ResourceReceivedData: 297,
  XHRReadyStateChange: 0.06899999999999999,
  XHRReadyStateChange_avg: 0.011499999999999998,
  XHRReadyStateChange_max: 0.015,
  XHRReadyStateChange_count: 6,
  ResourceFinish: 56,
  XHRLoad: 56.73,
  XHRLoad_avg: 56.73,
  XHRLoad_max: 56.73,
  XHRLoad_count: 1,
  TimerInstall: 21,
  ScheduleStyleRecalculation: 96,
  InvalidateLayout: 41,
  RecalculateStyles: 38.57400000000001,
  RecalculateStyles_avg: 0.38574000000000014,
  RecalculateStyles_max: 7.156,
  RecalculateStyles_count: 100,
  CancelAnimationFrame: 9,
  TimerFire: 4.015000000000001,
  TimerFire_avg: 0.3345833333333334,
  TimerFire_max: 1.205,
  TimerFire_count: 12,
  TimerRemove: 9,
  Layout: 18.626,
  Layout_avg: 0.4901578947368421,
  Layout_max: 3.269,
  Layout_count: 38,
  Paint: 7.433000000000003,
  Paint_avg: 0.07992473118279574,
  Paint_max: 0.441,
  Paint_count: 93,
  UpdateLayer: 12.53799999999999,
  UpdateLayer_avg: 0.06564397905759158,
  UpdateLayer_max: 0.48,
  UpdateLayer_count: 191,
  PaintImage: 1.467999999999998,
  PaintImage_avg: 0.009006134969325142,
  PaintImage_max: 0.09,
  PaintImage_count: 163,
  AnalyzeTask: 8.410999999999985,
  AnalyzeTask_avg: 0.010566582914572846,
  AnalyzeTask_max: 0.056,
  AnalyzeTask_count: 796,
  RasterTask: 534.6050000000002,
  RasterTask_avg: 1.0977515400410682,
  RasterTask_max: 16.537,
  RasterTask_count: 487,
  'Decode Image': 121.84900000000002,
  'Decode Image_avg': 2.707755555555556,
  'Decode Image_max': 26.164,
  'Decode Image_count': 45,
  'Decode LazyPixelRef': 219.27700000000004,
  'Decode LazyPixelRef_avg': 4.872822222222223,
  'Decode LazyPixelRef_max': 38.545,
  'Decode LazyPixelRef_count': 45,
  ImageDecodeTask: 231.9250000000001,
  ImageDecodeTask_avg: 5.153888888888891,
  ImageDecodeTask_max: 39.005,
  ImageDecodeTask_count: 45,
  'Draw LazyPixelRef': 52,
  CommitLoad: 0.114,
  CommitLoad_avg: 0.114,
  CommitLoad_max: 0.114,
  CommitLoad_count: 1,
  ParseAuthorStyleSheet: 13.526,
  ParseAuthorStyleSheet_avg: 1.69075,
  ParseAuthorStyleSheet_max: 6.859,
  ParseAuthorStyleSheet_count: 8,
  ParseHTML: 210.42999999999995,
  ParseHTML_avg: 0.6854397394136806,
  ParseHTML_max: 105.661,
  ParseHTML_count: 307,
  EvaluateScript: 170.62599999999998,
  EvaluateScript_avg: 4.265649999999999,
  EvaluateScript_max: 41.066,
  EvaluateScript_count: 40,
  MarkDOMContent: 1,
  MarkLoad: 1 }

**Comment by adokania** [comment]
It dos give me a list of stats but there is no meanFrameTime in that .. Has that been removed? What might be a good metric to keep track of  in that case?

**Comment by axemclion** [comment]
If you run `browser-perf` directly, you do see mean_frame_time and meanFrameTime. Can you update `protractor-perf`'s `browser-perf` dependency and check ?

**Comment by adokania** [comment]
I updated the version of browser-perf in protractor-perf from 1.2.4 to 1.2.8 and still dont see it ..Anything else I could do ?

**Comment by adokania** [comment]
These are a list of few stats i see

{ fetchStart: 1432665953786,
  redirectStart: 0,
  domComplete: 1432665976307,
  redirectEnd: 0,
  loadEventStart: 1432665976307,
  navigationStart: 1432665953786,
  requestStart: 1432665953787,
  responseEnd: 1432665974173,
  secureConnectionStart: 0,
  domLoading: 1432665974179,
  domInteractive: 1432665976105,
  domainLookupEnd: 1432665953786,
  domContentLoadedEventStart: 1432665976105,
  loadEventEnd: 1432665976309,
  connectEnd: 1432665953786,
  responseStart: 1432665974171,
  unloadEventStart: 1432665974173,
  domContentLoadedEventEnd: 1432665976206,
  connectStart: 1432665953786,
  unloadEventEnd: 1432665974173,
  domainLookupStart: 1432665953786,
  firstPaint: 20759.1428756714,
  Program: 1193.4449999999558,
  Program_avg: 0.12792850251902196,
  Program_max: 106.246,
......}

**Comment by axemclion** [comment]
that is weird - you should indeed be able to see meanFrameTime. An easier way to debug would be to set `export DEBUG=*` and then run it. That should tell us all the metrics that ran.

**Comment by axemclion** [comment]
@adokania - This could also be because the page loaded is a simple page, and is just drawn once. May be you can try opening some website that has more content, and does some actions. You could try the sample test case from the `test` directory and see if you see the metrics.

**Comment by adokania** [comment]
yea i guess that was it, but shouldn't it return 0 instead of not returning the stat at all. I did use the test in the protractor-perf directory to confirm that the meanFrameTime value is returned.

**Comment by axemclion** [comment]
@adokania - thats a good point. It used to return 0, but someone pointed out in `browser-perf` that meanFrameTime is technically not 0, it just could not be calculated. Not returning it gives undefined, which sort of means that we cannot define that number.
