### ISSUE TITLE
What measurement does perf.getStats('meanFrameTime') give ?? I mean i get a number for this but what is that number ? Is it number of seconds or Milliseconds ?

### ISSUE THREAD

**Issue by challapruthvi** [axemclion/protractor-perf#9]

**Comment by adokania** [comment]
It is in milliseconds --https://github.com/axemclion/browser-perf/wiki/Metrics

**Comment by challapruthvi** [comment]
Thank you !!

**Comment by challapruthvi** [comment]
When I try to log perf.getStats('meanFrameTime') I couldn't find the number but instead getting something like below: 

{ closure_uid_23342636: 226,
  flow_:
   { events_: {},
     closure_uid_23342636: 1,
     activeFrame_:
      { events_: {},
        closure_uid_23342636: 83,
        flow_: [Circular],
        parent_: [Object],
        children_: [Object],
        lastInsertedChild_: [Object],
        pendingTask_: null,
        isLocked_: false,
        isBlocked_: false,
        pendingCallback: false,
        pendingRejection: false,
        cancellationError_: null },
     schedulingFrame_:
      { events_: {},
        closure_uid_23342636: 83,
        flow_: [Circular],
        parent_: [Object],
        children_: [Object],
        lastInsertedChild_: [Object],
        pendingTask_: null,
        isLocked_: false,
        isBlocked_: false,
        pendingCallback: false,
        pendingRejection: false,
        cancellationError_: null },
     shutdownTask_: null,
     eventLoopTask_: null,
     hold_:
      { _idleTimeout: 2147483647,
        _idlePrev: [Object],
        _idleNext: [Object],
        _idleStart: 800983607,
        _onTimeout: [Function: wrapper],
        _repeat: true },
     yieldCount_: 7 },
  stack_: { [Task: <anonymous>] name: 'Task' },
  parent_: null,
  callbacks_: null,
  state_: 'pending',
  handled_: false,
  pendingNotifications_: false,
  value_: undefined }

How do I get the chrome metrics outputed ?? Is there any way to do that ?

**Comment by axemclion** [comment]
`perf.getStats()` returns a promise - you would need to do `perf.getStats().then(console.log.bind(console))` to get all the metrics.

**Comment by sadanandGithub123** [comment]
Hello I Tried Same , as you suggested but getting this error --
   Failed: erf is not defined

Please Suggest what can i do ?

**Comment by aicodess** [comment]
Hello 
When i run this Code--
perfRunner.getStats('meanFrameTime').then(function(time){
                           console.log(time);
)};

it always returns me time grater then complete test execution time is it possible ???

**Comment by axemclion** [comment]
@sadanandGithub123 MeanFrameTime is the average time (in ms) for each frame. This cannot be greater than the time for the entire test.

**Comment by maj2002** [comment]
When I run this I get this error:
 if (typeof browserConfig[passedBrowser.browserName] !== 'undefined') {

I have included these lines in my spec file:
var ProtractorPerf = require('protractor-perf');
var perf = new ProtractorPerf(protractor); // Initialize the perf runner

My conf file does define browserName:
    getMultiCapabilities : function () {
        return q.all([

```
        {
            'browserName': 'chrome',
            'chromeOptions' : { args: ['--test-type']},
            'loggingPrefs': {
                'browser': 'ALL'
            }
        },
]);
```

},

**Comment by maj2002** [comment]
Forgot to actually put the error...got the line that it was complining about.

Here is the error I get - even though I believe that I have browserName defined:

TypeError: Cannot read property 'browserName' of undefined
